site_name: Marp Documentation

repo_name: 'marp-group'
repo_url: 'https://github.com/marp-group/'

theme:
  name: material
  language: en
  logo:  assets/logo_fit.png
  favicon: assets/logo_fit.png
  
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      primary: orange
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: orange
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

markdown_extensions:
  - attr_list
  - md_in_html